package com.example.YourCircle.Domain;

import jakarta.persistence.*;

import java.sql.Date;

@Entity
public class Circle {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int circleId;   // unique id generated by database.
    @ManyToOne
    @JoinColumn(name="userId", nullable=false)
    private User user;
    private String circleName;
    private String circleDesc;
    private Date creationDate;

    public int getCircleId() {
        return circleId;
    }

    public void setCircleId(int circleId) {
        this.circleId = circleId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getCircleName() {
        return circleName;
    }

    public void setCircleName(String circleName) {
        this.circleName = circleName;
    }

    public String getCircleDesc() {
        return circleDesc;
    }

    public void setCircleDesc(String circleDesc) {
        this.circleDesc = circleDesc;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}
